instructions:
  heading: How to use your presets
  description: lorem Ipsum aute do minim nulla est ipsum anim qui laboris nostrud.Adipisicing magna consectetur in nisi aute sint occaecat et non deserunt. Aliqua est ipsum dolore duis sunt. Mollit Lorem aliquip ad duis minim excepteur elit minim do eiusmod quis. lorem Ipsum aute do minim nulla est ipsum anim qui laboris nostrud.Adipisicing magna consectetur in nisi aute sint occaecat et non deserunt. Aliqua est ipsum dolore duis sunt. Mollit Lorem aliquip ad duis minim excepteur elit minim do eiusmod quis.
  video: Placeholder
faq:
  - question: This is a question
    answer: This can be an answer for the question above. But we still don't know.
  - question: This is a question
    answer: This can be an answer for the question above. But we still don't know.
  - question: This is a question
    answer: This can be an answer for the question above. But we still don't know.
  - question: This is a question
    answer: This can be an answer for the question above. But we still don't know.